### ISSUE TITLE
Use FontAwesome

### ISSUE THREAD

**Issue by otacke** [msdlt/h5p.LinkedImageSwap#4]
I don't see any problems with H5P's FontAwesome library.

Have you used `font-family: H5PFontAwesome4;` as documented in the library's readme? Then `\f10c` and `\f192` should give you the icons that you're looking for.

https://github.com/msdlt/h5p.LinkedImageSwap/blob/89154dd522cd8726dba857e71e353a330a0e4b61/library.json#L24

**Comment by theotherdy** [comment]
Definitely tried that before, with no luck - not sure what's changed but now working - thank you!
