### ISSUE TITLE
Use of CC BY-SA

### ISSUE THREAD

**Issue by otacke** [msdlt/h5p.LinkedImageSwap#5]
I know that some example code on the specs page shows using the "Creative Commons BY-SA" license, but it's rather an odd license for source code. Are you using it intentionally?

https://github.com/msdlt/h5p.LinkedImageSwap/blob/89154dd522cd8726dba857e71e353a330a0e4b61/library.json#L10

**Comment by theotherdy** [comment]
You're right, thanks - just copied the tutorial licence code without thinking. Now MIT.
