### ISSUE TITLE
Why computing the width?

### ISSUE THREAD

**Issue by otacke** [msdlt/h5p.LinkedImageSwap#7]
What's your intention here?

Is it necessary to compute a fixed width and set it with every resize call, or could using flexbox solve your issue? https://css-tricks.com/snippets/css/a-guide-to-flexbox/

https://github.com/msdlt/h5p.LinkedImageSwap/blob/89154dd522cd8726dba857e71e353a330a0e4b61/linked-image-swap.js#L209

**Comment by theotherdy** [comment]
I'm afraid this was again just adapting H5P demo code: https://h5p.org/documentation/for-developers/responsive-design without thinking too much. I'll have a go with Flexbox later.

**Comment by otacke** [comment]
@theotherdy I see :-) Nothing wrong with that, but I can really recommend using a flexbox approach if you want to create a responsive layout. It's easier to understand for other coders who want to use your code and it allows others to customize the design to their needs by just overriding the CSS.

**Comment by theotherdy** [comment]
Thanks @otacke - flexbox now applied.

**Comment by otacke** [comment]
@theotherdy Glad you figured it out. I'd have to check if you could streamline your code even more, but I'll wait until you cleaned it up a little :-)
